/**
 * @file Find-the-Difference.cpp
 * @brief 寻找不同的字符(https://leetcode.com/problems/find-the-difference/)
 * @author Finalcheat
 * @date 2017-02-08
 */

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 */

/**
 * 用一个26大小的数组存储字符的出现次数，遍历s字符串构造字符出现次数，最后遍历t字符串查找对应位置的字符次数，若为0则为该字符。
 */

class Solution {
    public:
        char findTheDifference(string s, string t) {
            int arr[26];
            for (size_t i = 0; i < 26; ++i) {
                arr[i] = 0;
            }
            for (size_t i = 0; i < s.size(); ++i) {
                ++arr[s[i] - 'a'];
            }
            for (size_t i = 0; i < t.size(); ++i) {
                if (arr[t[i] - 'a']-- == 0) {
                    return t[i];
                }
            }
            return '@';
        }
};
